version: '3.8'

services:
  # Redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_net

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app_net

  # book-search service
  book-search:
    build: ./services/book-search
    container_name: book-search
    ports:
      - "3000:3000"
    env_file:
      - ./services/book-search/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - app_net

  # book-detail service
  book-detail:
    build: ./services/book-detail
    container_name: book-detail
    ports:
      - "3001:3000"
    env_file:
      - ./services/book-detail/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app_net

  # book-display service
  book-display:
    build: ./services/book-display
    container_name: book-display
    ports:
      - "3002:3000"
    env_file:
      - ./services/book-display/.env
    networks:
      - app_net

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Alokasi memori, penting!
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app_net

volumes:
  esdata:

networks: 
  app_net:
    driver: bridge